disabled_rules:
  - identifier_name
  - cyclomatic_complexity 
  - type_body_length
  - function_body_length
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ParsecTests
line_length: 200
