# disabled_rules:
#  - identifier_name
#  - cyclomatic_complexity
#  - function_body_length
whitelist_rules:
  - trailing_whitespace
  - colon
  - vertical_whitespace
  - shorthand_operator
  - redundant_optional_initialization
  - for_where
  - trailing_newline
  - unused_optional_binding
  - comma
  - opening_brace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  
line_length: 200
